# Generated by Django 3.2.13 on 2022-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_liking',
            field=models.ManyToManyField(related_name='article_liker', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_liking',
            field=models.ManyToManyField(related_name='comment_liker', to='articles.Comment'),
        ),
    ]
