# Generated by Django 3.2.13 on 2022-10-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='to_user',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='who',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='who', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_user', models.CharField(max_length=50)),
                ('last_message', models.TextField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='directmessage',
            name='room_number',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='chat.messageroom'),
            preserve_default=False,
        ),
    ]
