# Generated by Django 3.2.13 on 2022-10-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20221021_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
