# Generated by Django 3.2.13 on 2022-10-20 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_messageroom_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='messageroom',
            name='to_user',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='fromuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiveruser', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageroom',
            name='touser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='senduser', to='accounts.user'),
            preserve_default=False,
        ),
    ]
